name: Build and Deploy Code

# run on push and pull requests to all branches
on: [push, pull_request]

# job, on machine, and steps
jobs:
  job1:
    # job-specific env vars
    env:
      DATABASE_HOSTNAME: localhost
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: lizFastAp1
      DATABASE_NAME: fastapi
      DATABASE_USERNAME: postgres
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 60

    runs-on: ubuntu-latest
    steps:
      # Pull git repo using an action from the marketplace
      - name: pulling git repo # human readable name for the step
        uses: actions/checkout@v2 
      # eg of a second step
      # - name: say hi to Liz
      #   run: echo "hello Liz" # run any cmd on cli of this ubuntu machine

      # Install python
      - name: install Python version 3.9
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      # Upgdate pip from cli of the runner/VM
      - name: update pip
        run: python -m pip install --upgrade pip

      # Install dependencies from cli of runner
      - name: install all dependencies
        run: pip install -r requirements.txt
      
      # Install & run pytest
      - name: test with pytest
        run: | # pipe to run several commands
          pip install pytest
          pytest
          